Our large language model simulations are projections wherein *all* tourists’ decisions are made by generative AI.
They are hypothetical scenarios, far from the current reality.
However, we use these projections because they can illustrate how generative AI might reshape tourist flows, by isolating the patterns of generative AI-driven tourism and comparing them to empirical-based simulations.
Large language models produce tourist flow networks that diverge from the empirical patterns.
But the extent and direction of this divergence vary by model, challenging our initial proposition that generative AI amplifies existing tourist flow patterns.

@tbl-htest summarizes the hypothesis testing results and reports the characteristics of the two large language model simulations compared to empirical-based scenarios.
Both large language models produced more seasonal (H1) and less reciprocal (H3) tourist flows.
These models also produced slightly more centralized tourist flows (H2).
Such scenarios would increase the difficulty destinations face in managing demand imbalances between peak and off-peak seasons.
Additionally, currently popular domestic tourist destinations would gain further popularity, while less popular destinations would experience reduced tourist arrivals.
Combined with less reciprocal tourist flow, popular destinations would receive more tourists but send fewer to others, leading to a more "one-way" tourism system.
Although popular tourism destinations may view such shifts favorably, they must also consider the aggravation of tourism's negative impacts, including over-tourism and tourism-driven gentrification.

{{< include tables/_tbl-htest.qmd >}}
: Summary of hypothesis testing and characteristics of large language model simulations compared to empirical-based scenarios {#tbl-htest tbl-colwidths="[3,35,25,25,12]"}

Other characteristics of the large language model simulations are dependent on the model used.
Gemini 2.5 Flash Lite shows a level of intra-state tourism similar to the empirical-based scenarios (H6a and H6b).
But GPT-4.1 Nano produces tourist flows that have a much higher self-loop ratio (H6a).
The two models further diverge in travel distance (H4a and H4b) and visits to bordering states (H5a and H5b).
Other factors being equal, Gemini 2.5 Flash Lite shows stronger preferences for distant destinations and neighboring states.
GPT-4.1 Nano’s recommendations tend to be in-state and are less affected by distance and border effects.

Based on our main findings and robustness checks (Appendix \ref{apx-robust}), we conclude that geographic patterns of tourist flows generated by large language models are inconsistent.
As the underlying mechanisms of generative AI models are largely uninterpretable, one cannot pinpoint the reasons for these differences.
Nevertheless, a key takeaway is that all large language models consistently produce tourism patterns that differ from the network and geographic characteristics of real-world tourist flows.

## Implications

This study provides evidence that the adoption of generative AI has the potential to change the patterns of tourism at large.
Although this study does not directly address the possibility of algorithmic flattening [@lehto2025], generative AI can reinforce polarization of tourist flows, both temporally and geographically.
Our findings support @mellors2025 that large language models tend to recommend popular destinations, leading to a less sustainable tourism system.
We also reveal additional issues: generative AI can worsen demand seasonality and make the tourist flow network asymmetric.
These findings are preliminary evidence that generative AI poses significant potential to undermine tourism’s sustainability and warrant further investigation.

Future studies examining generative AI adoption in tourism (or any other generative AI) must consider its potential impact on the tourism system.
The technology can solve problems that tourists and practitioners face, while also introducing new issues [@dogru2025].
We echo the previous cautions that technology adoptions in tourism should not be seen as *progress* or *advancements*; rather, they are *changes* that we must navigate to assess their implications for all tourism stakeholders [@hur2022; @tribe2017].

We present an opportunity to shift the relationship between empirical phenomena of generative AI adoption in tourism and related tourism knowledge.
Currently, empirical phenomena of generative AI adoption outpace tourism knowledge production, due to generative AI's rapid evolution and academic publication delays.
This study demonstrates an alternative route: *a priori* knowledge production by tourism scholars that informs decision-making in tourism practice.
Such guiding knowledge will prove crucial for tourism scholarship and practitioners to ensure sustainable and resilient tourism systems amid rapid technological changes.



## Methodological contributions

To our knowledge, this is the first study that uses large language models to simulate tourist flows.
We use these simulations to project how generative AI would influence the patterns of tourist flows, rather than to replicate real-world tourist behaviors.
Our purpose therefore differs from suggestions adopting generative AI to generate synthetic data for substituting survey respondents [@viglia2024a].
Given the central tendency across 1,000 iterations, large language models can simulate tourism visits with consistency.
However, these AI models do not substitute empirical data collection; researchers must compare AI-generated data carefully to real-world tourist behaviors.
Researchers should also be aware of discrepancies among generative AI models.
In addition to being transparent about the specific model and parameter used for AI-generated data, we highly recommend testing the sensitivity of findings across different generative AI models.
While we employed large-scale simulations, researchers can use smaller-scale simulations for other tourism studies.
They may focus on a specific destination or tourist segment to obtain more detailed insights into generative AI's impact.

Another methodological contribution is examining the distribution of network characteristics over multiple iterations of simulated networks.
Tourism is a complex system, where the outcomes are probabilistic rather than deterministic [@faulkner2003].
As such, our approach acknowledges that even the observed tourism flow network is one of many possible outcomes.
By creating simulated realizations of the network under given conditions, we can better project the range of possible network structures and identify which observed patterns constitute robust features versus artifacts of stochastic variation.
But as the number of nodes and ties in a network increases, some of the network characteristics arise by chance alone.
For this reason, presenting a random model as a baseline is essential for interpreting the significance of observed patterns.
Beyond our equiprobable random model, we recommend considering other types of random networks based on the network under examination [see @baggio2008a].

## Practical suggestions

As society increasingly adopts generative AI, its influence will extend regardless of whether tourism sectors actively integrate these technologies.
Therefore, we urge tourism practitioners and regulators to monitor and prepare for generative AI’s potential impacts on tourist behavior and destination choice.
Such preparedness will become crucial for both established and emerging destinations.
For already-popular destinations, the expected challenges are managing the carrying capacity during the peak season and developing attractive off-season offerings.
Lesser-known destinations confront more complex obstacles.
Generative AI models train on extensive cross-domain datasets, making their outputs difficult to alter.
Instead, we recommend that lesser-known destinations diversify their marketing channels and explore partnerships with online influencers who can reach targeted audiences while bypassing algorithmic barriers.

Generative AI has the potential to shift the trajectory of tourism.
We thus recommend that national and international tourism organizations begin assessing implications of generative AI adoption, particularly related to the sustainability and resilience of tourism.
Organizations must recognize that tourism functions not merely as a "market offering" but as a societal force affecting people and communities [@higgins-desbiolles2006].
For example, one social benefit of tourism is that it provides experiences and opportunities for socially excluded groups [@mccabe2020a].
These benefits may diminish in imbalanced tourism systems, such as those seen in our generative AI-driven scenarios, where popular destinations continue to grow, smaller destinations are overshadowed, and tourist exchange between regions becomes increasingly unbalanced.
While we caution generative AI's potential consequences for tourism, the time is right to proactively shape the future of tourism before generative AI is further integrated into tourism industries.
Our projected generative AI-driven tourism is still hypothetical; it is up to us whether such a future may never come to pass.

## Limitations and future research

Consider the following key limitations when interpreting our findings.
First, our large language model simulations rely solely on demographic factors and exclude psychological, behavioral, and social variables that shape tourist decisions.
One of which is tourist motivation.
Even if two individuals with an identical demographic profile visited the same destination, they could have entirely different motivations for visiting.
Consequently, our findings only provide a general view of tourist flows generated by generative AI.
Future research could consider specifying preferences and motivations for each simulated tourist [see @gao2024].
Such specifications will further require real-world data on factors such as tourists' travel purpose, histories, and constraints.
In addition, simulations could incorporate different rates of accepting AI-generated recommendations for more realistic projections.
For instance, younger individuals are generally more inclined to accept generative AI recommendations compared to older individuals [@seyfi2025], which could result in different travel patterns than those observed in our "extreme-case" scenarios.

Our simulations assume that everyone travels and selects a single destination.
But we must consider that there are non-travelers who choose not to travel [@haukeland1990] and tourists visiting multiple destinations during a single trip [@yang2013].
One tourist's decision can also influence the decisions of others [@lee2025a], although our simulations do not account for interactions between simulated individuals.

Finally, the results are subject to the modifiable areal unit problem, as the choice of geographic unit affects the results [@fotheringham1991].
Large language models recommended destinations in varying geographic units, which we aggregated to the state level for analyses.
This aggregation masks variations at finer geographic scales, thus likely underestimates the differences between the empirical and generative AI-driven scenarios.
Future research could examine the impact of generative AI on individual tourists or attractions within a specific destination, which would be more suitable for exploring other dimensions of generative AI's impact, such as ethical issues, social inequality, and environmental sustainability.