## Assessing the impact of generative AI on the tourist flow network

Empirical insights on how generative AI is reshaping tourism are limited, but tackling this gap is challenging.
We begin by narrowing down this study's scope.
Our study focuses on generative AI's impact on tourist flow—the movement of tourists between different regions.
Tourism is a multifaceted phenomenon, crossing different academic disciplines [@tribe1997].
Inevitably, generative AI's impact on tourism will span multiple aspects, including tourist motivation, tourism geographies, and socio-economic implications.
The analysis of tourist flow touches major elements of the tourism system, including tourist-generating and -receiving regions and transit routes between them [@khalilzadeh2022; @leiper1979].
Understanding generative AI's influence on tourist flow therefore provides a foundation for assessing its broader tourism implications.

Specifically, we analyze tourist flow as a social network. 
In network science, entities such as persons, organizations, and regions are examined based on their interactions [@scott2008].
Unlike traditional social science methods, network science treats entities ("nodes") and relationships ("edges") as interdependent rather than isolated [@wasserman1994].
Despite its potential, tourism studies have underutilized the network science approach [see @baggio2017; @demartino2024].
Nevertheless, several studies have provided insights into characteristics of tourist flow networks and their implications for tourism research [e.g., @baggio2020a; @khalilzadeh2022; @liu2017; @shih2006].
These prior works inform our investigation of generative AI's potential impact on tourism patterns, while considering the complexities and interdependencies surrounding tourism as a network phenomenon.


## Scenario-based projection models

We needed a sound empirical approach that accounts for the intricate relationship between generative AI and its users, as well as the inherent probabilistic nature of generative AI.
Beyond generative AI, tourism is influenced by factors like seasonality, economic conditions, and changes in tourist preferences, among other things.
We also have limited data on tourists’ generative AI usage and the extent of its influence on travel decisions.

To tackle these challenges, we use scenario-based projection models that answer the following question: *What will happen if all tourist flows are determined by generative AI?*
Most models we see in social science are explanatory; models that are designed to explain the relationship between how one thing leads to another [@frigg2025].
Explanatory models are useful for understanding why something happened, but they require analyzing past events. 
This "temporally backwards-facing" nature of explanatory modeling makes it less applicable for predicting something that has not yet occurred [@adams2020a].

Scenario-based projection models predict outcomes under specified conditions [@runge2024].
Examples include Shared Socioeconomic Pathways for climate trajectories [@ipcc2021] and COVID-19 diffusion models [@adam2020].
These models contain “worst-case” scenarios that project the most extreme outcomes: climate projections without emission reductions or infection rates without government interventions.
Though unrealistic, these extreme scenarios serve as benchmarks for assessing whether action is necessary. 
We apply this approach that projects a scenario where generative AI makes all tourist decisions.
This scenario quantifies the ceiling of generative AI's impact on tourist flow, which can help determine whether widespread generative AI adoption in tourism merits optimism or caution.

## Hypotheses development

Before hypothesizing how generative AI will change tourism patterns, we must first establish what existing characteristics define tourist flow networks.
Networks can be analyzed at different levels: individual nodes, subsets of nodes, or the entire network [@baggio2020a]. 
Accordingly, network characteristics can be examined across these analytical levels.
To understand the broader structural impact of generative AI on tourism, we focus on network-level characteristics that capture the overall structure of tourist flows.

We propose six hypotheses testing how specific features of the tourist flow network change under generative AI-driven scenarios. 
These are not exhaustive, but rather a subset of characteristics that are chosen for their theoretical significance and practical relevance.
Given the multifaceted nature of tourism phenomena, no single theory can account for all six aspects of tourist flows examined here [see @lee2025a].
Instead, we draw on multiple existing theories and empirical findings to inform each of our hypotheses.
To clarify, the purpose of using these theories is not to develop a new theory to explain and predict the impacts of generative AI on tourist flows.
Such attempts would be counterproductive, given the “black-box” nature and constant evolution of generative AI.
Rather, we use theories to explain characteristics of tourist flows expected and why we expect them.
From there, we hypothesize how these characteristics will change under the generative AI-driven scenario.

The hypotheses are grounded in the proposition that *generative AI will amplify the existing characteristics of tourist flow networks.*
We base this proposition on generative AI's design and training data.
Generative AI models are optimized to produce highly probable outputs based on the input they receive [@ibm2023].
Consequently, their outputs primarily represent the characteristics of mainstream behaviors, whereas niches are underrepresented [@wu2024a; @yogarajan2023].
Moreover, these models are primarily trained on data available on the internet.
Online content tends to overrepresent popular behaviors and opinions while underrepresenting less popular alternatives [@gao2015; @hargittai2020].
This skewness in data perpetuates in generative AI's outputs, further amplifying the bias towards the behaviors of many [@shahbazi2023].
We chose *amplify* over *benefits* or *risks* because outcomes affect stakeholders differently—the same outcome may benefit specific destinations while harming the sustainability of the rest. 

### Changes in the distribution of tourist flows over time, space, and dyadic relationships

The first three characteristics examine the distribution of tourist flows over time, space, and dyadic relationships.
These characteristics are chosen for their relevance to the sustainability and resilience of destinations.
First is seasonality.
@butler1994 noted that "seasonality has long been recognized as one of the most distinctive features of tourism" (p. 332).
Tourist flows fluctuate between seasons, creating challenges for tourism industries to manage the demand [@duro2016].
Despite well-documented seasonality in tourism, its theoretical foundation remains underdeveloped [@senbeto2024].
Some scholars adopted Leisure Constraint Theory to explain seasonality arising from intra-personal, inter-personal, and structural constraints [@hinch2000].
Others have explained seasonality using the Push-Pull model, where factors like climate "push" tourists and "pull" them to certain destinations during a specific time of the year [@ridderstaat2014].
Given our proposition, we hypothesize that generative AI will amplify the seasonality in tourist flows.

***Hypothesis 1.** The generative AI-driven scenario will show higher seasonality in tourist flow than the empirical scenario.*

Tourist flows also tend to concentrate in popular destinations.
Such concentration exists not only between destinations but also within a destination [@cheng2025].
Network studies in tourism provide empirical evidence that such concentration occurs universally in tourist flow networks [@baggio2020a; @khalilzadeh2022].
Agglomeration theory from economic geography predicts that tourist attractions tend to cluster together to reap benefits from proximity to each other, leading to geographic concentration of tourist flows [@majewska2015].
Another explanation comes from network science, where the preferential attachment mechanism leads to a few nodes accumulating most of the connections in a network [@barabasi1999].
Spatial concentration of tourist flows can also be explained by social influence, which makes tourists flock to popular destinations [@lee2025a].
We hypothesize that this spatial concentration of tourist flows over space will be more pronounced in generative AI-driven scenarios.

***Hypothesis 2.** The generative AI-driven scenario will show a higher concentration of tourist flows in popular destinations than the empirical scenario.*

Beyond temporal and spatial concentration, network analysis allows us to examine dyadic patterns in tourist flows.
Although less studied in tourism, reciprocity is a common characteristic of social networks where entities tend to form mutual relationships [@wasserman1994].
Despite reciprocity being a fundamental mechanism in many social networks [@squartini2013], inter-regional interactions like migration and bilateral trade have shown mixed evidence of reciprocity [@leal2021; @setayesh2022].
Tourist flow networks would exhibit asymmetrical flows from less popular regions to a few popular destinations, given the spatial concentration of tourist visits.
Since we hypothesize that the generative AI-driven scenario will show more concentrated tourist flows towards popular destinations, we also expect greater asymmetries in generative AI-driven tourist flow networks.

***Hypothesis 3.** The generative AI-driven scenario will show fewer reciprocal tourist flows than the empirical scenario.*

### Changes in geographic patterns of tourist flows

As @tobler1970 observed, “near things are more related than distant things.”
This phenomenon of distance decay is later formalized as the First Law of Geography, which became a foundational principle in spatial analysis.
Tourism scholars have long recognized the significance of this law in explaining tourist flows [@mckercher2018a], embedded in foundational models like the gravity model of tourism [@morley2014].
Studies consistently evidence that the tourist volume between two regions is inversely proportional to the physical distance between them [@mckercher2003a; @yang2023e].
Such a proximity effect can also be modeled in a nominal way, with tourist visits occurring more frequently between regions sharing borders [@rossello-nadal2022].
Geographic proximity also makes intra-regional travel more common [@alvarez-diaz2024], termed *self-loops* in network analysis.
If we define destinations as countries, self-loops are domestic tourism within those nations.
Based on our proposition, we hypothesize that these geographic patterns explained by distance decay will be more salient in generative AI-driven tourist flow networks.

***Hypothesis 4a.** The generative AI-driven scenario will show lower mean travel distances than the empirical scenario.*

***Hypothesis 5a.** The generative AI-driven scenario will show a higher proportion of flows to bordering regions than the empirical scenario.*

***Hypothesis 6a.** The generative AI-driven scenario will show a higher proportion of self-loops than the empirical scenario.*

However, travel distance, border adjacency, and self-loops are highly interdependent.
For example, increasing tourist flows to neighboring regions will reduce the mean travel distance.
To account for these interdependencies, we test additional hypotheses examining each geographic factor while controlling for the other two.

***Hypothesis 4b.** Holding border adjacency and self-loop constant, the generative AI-driven scenario will show stronger negative effects of travel distance on tourist flow than the empirical scenario.*

***Hypothesis 5b.** Holding travel distance and self-loop constant, the generative AI-driven scenario will show stronger positive effects of border adjacency on tourist flow than the empirical scenario.*

***Hypothesis 6b.** Holding travel distance and border adjacency constant, the generative AI-driven scenario will show stronger positive effects of self-loops on tourist flow than the empirical scenario.*